from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

OUTPUT_DIR = PROJECT_ROOT / "output"

DEFAULT_CELL_VOLTAGE_COUNT = 416
DEFAULT_CELL_TEMPERATURE_COUNT = 256
DEFAULT_TEMPERATURE_MODE = "diff"
DEFAULT_SOC_CELL_TYPE = 305
DEFAULT_SOC_CAL_TYPE = "dch"
DEFAULT_REST_CURRENT_THRESHOLD_A = 5.0
DEFAULT_REST_MAX_VOLTAGE = 3.3
DEFAULT_REST_DURATION_HOURS = 1.0
